

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: node index.js
