name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Define o ambiente do runner (ou use ubuntu-latest)
    environment: dev

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}  # <-- variável TOKEN do Environment "dev"

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/experimental-app:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/experimental-app:latest

      - name: Deploy (opcional)
        run: |
          echo "Aqui você pode adicionar seu script de deploy"
          # Exemplo: docker-compose up -d
