name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Define o ambiente do runner (pode ser ubuntu, windows, macos)

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2  # Faz o checkout do repositório para o runner

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23'  # Defina a versão do Node.js que seu projeto usa

    - name: Install dependencies
      run: npm install  # Instala as dependências do seu projeto

    - name: Build project
      run: npm run start  # Compila seu projeto, se necessário (ajuste conforme necessário)

    - name: Deploy (opcional)
      run: |
        echo "Aqui você pode adicionar seu script de deploy"
        # Por exemplo, você pode adicionar um comando para fazer deploy do projeto